# http://akeil.net/listings/beets.config.yaml.html

# https://github.com/geigerzaehler/beets-alternatives
# https://github.com/vmassuchetto/beets-ydl
# https://github.com/mdorman/beets-userrating
# https://github.com/lrnt/beets-syncpl
# https://github.com/mschuerig/beets-top

directory: /Users/Roman/Documents/Audio/Music
library: /Users/Roman/Documents/Audio/.musiclibrary.db

import:
    # write metadata to music files
    write: yes 

    # move imported files from source to the music directory
    move: yes
    copy: no
    delete: no

    # use auto-tagging where possible
    # do not require confirmation on strong matches
    autotag: yes
    timid: no

    resume: ask
    incremental: no
    none_rec_action: ask
    log: /Users/Roman/Documents/Audio/.beet.log
    bell: yes

# use the release-date of the original (first) release of an album?
original_date: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# filename for the album art
art_filename: cover  # results in "cover.jpg"

# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no

# User Interface -------------------------------------------------------------

color: yes
list_format_item: %upper{$artist} - $album - $track. $title
list_format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    terminal_width: 80
    length_diff_thresh: 10.0

# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: []
        media: []
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30


# Plugins --------------------------------------------------------------------

plugins: [
  discogs,
  play,
  types,
  info,
  spotify,
  convert,
  #playlist,
  smartplaylist, #beet splupdate
  lyrics,
  fetchart,
  embedart, 
  lastgenre, # The lastgenre plugin fetches tags from Last.fm
  scrub, # remuve usless tags
  mbsync, #increes import speed
  #mpdupdate, #automatically update MPD’s index whenever you change your beets library.
  #mpdstats, collects statistics about your listening habits from MPD
  chroma, #analyze file use CPU
  missing
  
]

discogs:
  user_token: wNexhRhhbHDkwNmbpcFasOIgBGEXHUWTdOAOrIXs

play:
    command: /Applications/clementine.app/Contents/MacOS/clementine
    
types:
    rating: int
    love: bool
spotify:
    source_weight: 0.7
    mode: open
    show_failures: on
    tiebreak: first

convert:
  auto: no
  tmpdir: /Users/Roman/Documents/Audio/Converted/tmp
  dest: /Users/Roman/Documents/Audio/Converted/
  formats:
    mp3_320:
      command: ffmpeg -i $source -y -vn -b:a 320k $dest
      extension: mp3
    aac_192:
      command: afconvert -f m4af -d aac -b 192000 $source -o $dest
      extension: aac
    aac_320:
      command: afconvert -f m4af -d aac -b 320000 $source -o $dest
      extension: aac


playlist:
    auto: no
    relative_to: /Users/Roman/Documents/
    playlist_dir: /Users/Roman/Documents/Audio/Playlists

smartplaylist:
    relative_to: 
    playlist_dir: /Users/Roman/Documents/Audio/Playlists
    forward_slash: no
    playlists:
        - name: "Last 2 Wks.m3u"
          query: 'added- added:-2w..'
        - name: "Last Month.m3u"
          query: added- added:-1m..
        - name: "Loved Songs.m3u"
          query: love:True
        - name: "Rate 4-5.m3u"
          query: rating:4..5
        - name: all.m3u
          query: ''
        - name: porn.m3u
          query: 'artist:Порнофильмы'

lyrics:
    auto: yes
    fallback: ''

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder

scrub:
    auto: yes

embedart:
    auto: yes
    maxwidth: 300

lastgenre:
    count: 3

# required for mpdstats
mpd:
    host: localhost
    port: 6600
    password: "8278" # none

mpdstats:
    rating: False
    # two ratings are calculated:
    # "rolling" based on recent development
    # "stable" based on all-time development
    # rating mix 0.0 is all "rolling", 1.0 is all "stable"
    rating_mix: 0.75

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

chroma:
    auto: yes
acoustid:
    apikey: MtXUY1oVV0



